### PR TITLE
Create popup window feature PR#10

### PR DESCRIPTION
**Pull request by efmomoh**
Created window popup feature
for:

- [ ] Mobile
- [ ] Desktop

### CODE REVIEW

**Review by rotimiazeez — COMMENTED** [review]
# Hi @efmomoh, 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Please note that this is a pair-programming activity and it should be done with your partner. Kindly ensure there is a contribution from your partner to complete the requirement for this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by efmomoh** [comment]
Hi Team @rotimiazeez ,
I am asking that you kindly consider the review process; I have been emailed by Student Success to proceed with this week's activities solo.

Kindly contact Student Success for more info.

**Review by nedjwab — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi  @efmomoh                  👋

Your project is complete! ✔️✔  🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors


- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by efmomoh** [comment]
Hi Team Reviewer, 

I have been asked by Student Success to continue this week solo. Meanwhile, I don't have a coding partner for the remaining working days in this block. So kindly review my code; thanks for your understanding.

**Comment by efmomoh** [comment]
Thank you @nedjwab for the feedback...

**Pull request merged**
